modLoader = "javafml"
loaderVersion = "[41,)"
issueTrackerURL = "https://github.com/teamfusion/spyglassplus/issues"
license = "MIT (Code); All Rights Reserved (Assets)"

[[mods]]
modId = "spyglassplus"
version = "${version}"
displayName = "Spyglass+"
authors = "Team Fusion"
displayURL = "https://curseforge.com/minecraft/mc-mods/spyglassplus"
updateJSONURL = "https://gist.githubusercontent.com/andantet/1e2d4b00f3f6fa88c5118aff7d7c0f08/raw/spyglassplus.json"
description = '''
A Minecraft mod that adds to and improves the Spyglass experience!
'''
logoFile = "icon.png"

[[dependencies.spyglassplus]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spyglassplus]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spyglassplus]]
modId = "architectury"
mandatory = true
versionRange = "[6.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.spyglassplus]]
modId = "cloth_config"
mandatory = true
versionRange = "[8.0,)"
ordering = "AFTER"
side = "BOTH"
